# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-BF2S
version:      0.03
version_from: lib/WWW/BF2S.pm
installdirs:  site
requires:
    Data::Dumper:                  2.121
    LWP::Simple:                   1.41
    XML::Simple:                   2.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
